services:
    CleverAge\LayoutBundle\Debug\DebugHtmlBlockRenderer:
        decorates: CleverAge\LayoutBundle\Templating\BlockRenderer
        autowire: true
        arguments:
            $baseBlockRenderer: '@CleverAge\LayoutBundle\Debug\DebugBlockRenderer.inner'

    CleverAge\LayoutBundle\Debug\DebugHtmlSlotRenderer:
        decorates: CleverAge\LayoutBundle\Templating\SlotRenderer
        autowire: true
        arguments:
            $baseSlotRenderer: '@CleverAge\LayoutBundle\Debug\DebugSlotRenderer.inner'
