services:
    clever_age.layout.event.layout_listener:
        class: CleverAge\LayoutBundle\EventListener\LayoutListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_subscriber }
