services:
    CleverAge\LayoutBundle\Registry\BlockRegistry:
        public: false
        autowire: true

    CleverAge\LayoutBundle\Registry\LayoutRegistry:
        public: false
        autowire: true
