services:
    clever_age_layout.registry.block:
        class: CleverAge\LayoutBundle\Block\BlockRegistry

    clever_age_layout.registry.layout:
        class: CleverAge\LayoutBundle\Layout\LayoutRegistry
        arguments:
            - '@clever_age_layout.factory.layout'
