services:
    CleverAge\LayoutBundle\Registry\BlockRegistry:
        public: false
        autowire: true

    CleverAge\LayoutBundle\Layout\LayoutRegistry:
        public: false
        autowire: true
